// Package capacity implements the static RSS profile table and admission
// control logic described in design decision D10.
//
// The profile table is checked into source and regenerated by scripts/measure-rss.sh.
// It is the sole input to capacity prediction; no live measurements are made at
// admission time.
package capacity

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// MB is a convenience constant.
const MB = 1

// ─── Profile table ───────────────────────────────────────────────────────────

// Key uniquely identifies an (broker_kind, throughput_tier, ingest_direction)
// combination in the profile table.
type Key struct {
	BrokerKind string // "mosquitto" | "emqx"
	Tier       string // "low" | "mid"
	Direction  string // "uni" | "bi"
}

// Profile holds the predicted RSS in MB for a single site matching the key.
type Profile struct {
	BrokerMB int // RSS for the broker container
	IngestMB int // RSS for all ingest container replicas combined
}

// TotalMB returns the sum of broker + ingest RSS.
func (p Profile) TotalMB() int { return p.BrokerMB + p.IngestMB }

// hostOverheadMB is the fixed RSS reserved for Docker engine + Traefik +
// controlai daemon + OS. Source: design decision D10.
const hostOverheadMB = 530

// perTenantTSDBMB is the RSS consumed per tenant by its TimescaleDB container.
// Source: D10 (Postgres with 64 MB shared_buffers).
const perTenantTSDBMB = 350

// maxUsableFraction is the fraction of usable RAM that can be allocated to
// tenant workloads before admission is denied (15 % headroom = 85 % usable).
const maxUsableFraction = 0.85

// profiles is the static RSS profile table (values in MB).
// Regenerate with scripts/measure-rss.sh; values must be within ±15 % of the
// measured baseline (enforced by TestProfileTableBaseline in profile_test.go).
//
// Row layout: Key → Profile{BrokerMB, IngestMB}
// bi direction adds 20 MB to IngestMB vs uni.
var profiles = map[Key]Profile{
	{BrokerKind: "mosquitto", Tier: "low", Direction: "uni"}: {BrokerMB: 20, IngestMB: 60},
	{BrokerKind: "mosquitto", Tier: "low", Direction: "bi"}:  {BrokerMB: 20, IngestMB: 80},
	// mosquitto + mid is rejected by the capability matrix; no entry.
	{BrokerKind: "emqx", Tier: "low", Direction: "uni"}: {BrokerMB: 400, IngestMB: 60},
	{BrokerKind: "emqx", Tier: "low", Direction: "bi"}:  {BrokerMB: 400, IngestMB: 80},
	{BrokerKind: "emqx", Tier: "mid", Direction: "uni"}: {BrokerMB: 450, IngestMB: 120},
	{BrokerKind: "emqx", Tier: "mid", Direction: "bi"}:  {BrokerMB: 450, IngestMB: 140},
}

// SiteProfile returns the predicted RSS for a single site. Returns an error
// for unknown or capability-matrix-rejected combinations.
func SiteProfile(brokerKind, tier, direction string) (Profile, error) {
	k := Key{BrokerKind: brokerKind, Tier: tier, Direction: direction}
	p, ok := profiles[k]
	if !ok {
		return Profile{}, fmt.Errorf("no capacity profile for broker=%s tier=%s direction=%s "+
			"(invalid combination or capability-matrix-rejected)", brokerKind, tier, direction)
	}
	return p, nil
}

// AllProfiles returns a copy of the entire profile table.
func AllProfiles() map[Key]Profile {
	out := make(map[Key]Profile, len(profiles))
	for k, v := range profiles {
		out[k] = v
	}
	return out
}

// ─── Plan & Admission ─────────────────────────────────────────────────────────

// TenantPlan represents a tenant (existing or proposed) with its sites.
type TenantPlan struct {
	TenantID string
	Sites    []SitePlan
}

// SitePlan represents a single site within a tenant plan.
type SitePlan struct {
	SiteID     string
	BrokerKind string
	Tier       string
	Direction  string
}

// Prediction is the output of Predict().
type Prediction struct {
	// TotalUsableMB is the usable RAM (MemTotal - host_overhead).
	TotalUsableMB int
	// MaxAllowedMB is TotalUsableMB * maxUsableFraction (85 %).
	MaxAllowedMB int
	// ProjectedMB is the sum of all tenant TSDB RSS + all site RSS.
	ProjectedMB int
	// Admissible is true when ProjectedMB ≤ MaxAllowedMB.
	Admissible bool
	// Headroom is MaxAllowedMB - ProjectedMB (can be negative when denied).
	HeadroomMB int
	// Breakdown is the per-tenant prediction breakdown (for debugging).
	Breakdown []TenantBreakdown
}

// TenantBreakdown holds per-tenant predicted consumption.
type TenantBreakdown struct {
	TenantID  string
	TsdbMB    int
	SitesMB   int
	TotalMB   int
	SiteBreakdown []SiteBreakdown
}

// SiteBreakdown holds per-site predicted consumption.
type SiteBreakdown struct {
	SiteID   string
	BrokerMB int
	IngestMB int
	TotalMB  int
}

// Predict computes the projected RAM usage for the given set of tenants and
// returns an Prediction. memTotalKB is /proc/meminfo MemTotal in kB.
func Predict(tenants []TenantPlan, memTotalKB int64) (Prediction, error) {
	usableMB := int(memTotalKB/1024) - hostOverheadMB
	if usableMB < 0 {
		usableMB = 0
	}
	maxAllowed := int(float64(usableMB) * maxUsableFraction)

	pred := Prediction{
		TotalUsableMB: usableMB,
		MaxAllowedMB:  maxAllowed,
	}

	for _, t := range tenants {
		tb := TenantBreakdown{TenantID: t.TenantID, TsdbMB: perTenantTSDBMB}
		pred.ProjectedMB += perTenantTSDBMB
		for _, site := range t.Sites {
			p, err := SiteProfile(site.BrokerKind, site.Tier, site.Direction)
			if err != nil {
				return Prediction{}, fmt.Errorf("predict: tenant %s site %s: %w", t.TenantID, site.SiteID, err)
			}
			sb := SiteBreakdown{
				SiteID:   site.SiteID,
				BrokerMB: p.BrokerMB,
				IngestMB: p.IngestMB,
				TotalMB:  p.TotalMB(),
			}
			tb.SitesMB += p.TotalMB()
			pred.ProjectedMB += p.TotalMB()
			tb.SiteBreakdown = append(tb.SiteBreakdown, sb)
		}
		tb.TotalMB = tb.TsdbMB + tb.SitesMB
		pred.Breakdown = append(pred.Breakdown, tb)
	}

	pred.Admissible = pred.ProjectedMB <= maxAllowed
	pred.HeadroomMB = maxAllowed - pred.ProjectedMB
	return pred, nil
}

// ─── /proc/meminfo reader ────────────────────────────────────────────────────

// ReadMemTotalKB reads MemTotal from /proc/meminfo (Linux only).
// On non-Linux hosts it returns a safe default (4 GiB) so tests compile cross-platform.
func ReadMemTotalKB() (int64, error) {
	f, err := os.Open("/proc/meminfo")
	if err != nil {
		// Non-Linux: return 4 GiB safe default
		return 4 * 1024 * 1024, nil //nolint:nilerr
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "MemTotal:") {
			var kb int64
			_, err := fmt.Sscanf(line, "MemTotal: %d kB", &kb)
			if err != nil {
				return 0, fmt.Errorf("parse MemTotal: %w", err)
			}
			return kb, nil
		}
	}
	return 0, fmt.Errorf("MemTotal not found in /proc/meminfo")
}
